typography_spectrum: 0.35757
color:
  brandColors:
    - '#ffffff'
    - '#b7c6c6'
    - '#f1f4f4'
    - '#e1e7e7'
    - '#ced8d8'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a2de019-b893-45d1-a1e4-7c6317c2f50c.svg
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d9627939-6bd3-4583-8f7c-c95b932693d5.svg
name: Dulcett
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/adeb8cd9-52e5-46da-8c3a-3e399c907520.jpg
purpose: []
