typography_spectrum: 0.35757
color:
  brandColors:
    - '#ffffff'
    - '#b7c6c6'
    - '#f1f4f4'
    - '#e1e7e7'
    - '#ced8d8'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Dulcett
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/579b04c2-98ee-4498-9355-9647b54e0084.png
purpose: []
